include: package:lints/recommended.yaml

formatter:
  page_width: 120
  
linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - avoid_print
    - sort_pub_dependencies
